/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.salle.custommoodle.view;

/**
 *
 * @author juanp
 */
public class StudentsWindow extends javax.swing.JFrame {

    /**
     * Creates new form StudentsWindow
     */
    public StudentsWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPNombre = new javax.swing.JTextField();
        txtSNombre = new javax.swing.JTextField();
        txtPApellido = new javax.swing.JTextField();
        txtSApellido = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        btnHombre = new javax.swing.JRadioButton();
        btnMujer = new javax.swing.JRadioButton();
        txtCURP = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("P Nombre");

        jLabel2.setText("S Nombre");

        jLabel3.setText("P Apellido");

        jLabel4.setText("S Apellido");

        jLabel5.setText("Estado");

        jLabel6.setText("DOB");

        jLabel7.setText("Sexo");

        jLabel8.setText("CURP");

        txtPNombre.setText("P Nombre");

        txtSNombre.setText("S Nombre");

        txtPApellido.setText("P Apellido");

        txtSApellido.setText("S Apellido");

        txtEstado.setText("Estado");

        txtDOB.setText("yymmdd");

        btnHombre.setText("Hombre");
        btnHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHombreActionPerformed(evt);
            }
        });

        btnMujer.setText("Mujer");
        btnMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMujerActionPerformed(evt);
            }
        });

        txtCURP.setText("CURP");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMujer))
                                    .addComponent(txtCURP, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtDOB, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEstado, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSApellido))
                                        .addGap(58, 58, 58))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPApellido))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSNombre)))
                                .addGap(58, 58, 58)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(btnRegistrar)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnHombre)
                    .addComponent(btnMujer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCURP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        char name= this.txtPNombre.getText().charAt(0);
        String lastName1=this.txtPApellido.getText();
        String lastName2=this.txtSApellido.getText();
        String firstName= this.txtPNombre.getText();
        String middleName=this.txtSNombre.getText();
        
        String ln1 = (Character.toString(this.txtPApellido.getText().charAt(0))+Character.toString(this.txtPApellido.getText().charAt(1)));
        char ln2 = this.txtSApellido.getText().charAt(0);
//        String year=this.txtYear.getText();
//        String month=this.txtMonth.getText();
//        String day=this.txtDay.getText();
        String DOB=this.txtDOB.getText();
       char mI=firstName.charAt(0);
        for(int i=0; i<firstName.length();i++)
        {
            if (mI!='A'&&mI!='E'&&mI!='I'&&mI!='O'&&mI!='U')
            {
                mI=firstName.charAt(i);
            }
        }
        String rfc = ln1+ln2+(firstName=="JOSE"||firstName=="MARIA"? mI:name)+DOB;
        String state = this.txtEstado.getText();
        String mIPA;
        if(lastName1.charAt(1)!='A' &&lastName1.charAt(1)!='E' && lastName1.charAt(1)!='I'&&lastName1.charAt(1)!='O' && lastName1.charAt(1)!='U')
        {
            mIPA = Character.toString(lastName1.charAt(1));
        }
        else
            if (lastName1.charAt(2)!='A' &&lastName1.charAt(2)!='E' && lastName1.charAt(2)!='I'&&lastName1.charAt(2)!='O' && lastName1.charAt(2)!='U')
            {
            mIPA = Character.toString(lastName1.charAt(2));
            }
        else
                 mIPA = Character.toString(lastName1.charAt(3));
        String mISA;
        if(lastName2.charAt(1)!='A' &&lastName2.charAt(1)!='E' && lastName2.charAt(1)!='I'&&lastName2.charAt(1)!='O' && lastName2.charAt(1)!='U')
        {
            mISA = Character.toString(lastName2.charAt(1));
        }
        else
            if (lastName2.charAt(2)!='A' &&lastName2.charAt(2)!='E' && lastName2.charAt(2)!='I'&&lastName2.charAt(2)!='O' && lastName2.charAt(2)!='U')
            {
            mISA = Character.toString(lastName2.charAt(2));
            }
        else
                 mISA = Character.toString(lastName2.charAt(3));
        String mIN;
        if(firstName.charAt(1)!='A' &&firstName.charAt(1)!='E' && firstName.charAt(1)!='I'&&firstName.charAt(1)!='O' && firstName.charAt(1)!='U')
        {
            mIN = Character.toString(firstName.charAt(1));
        }
        else
            if (firstName.charAt(2)!='A' &&firstName.charAt(2)!='E' && firstName.charAt(2)!='I'&&firstName.charAt(2)!='O' && firstName.charAt(2)!='U')
            {
            mIN = Character.toString(firstName.charAt(2));
            }
            else 
                mIN= Character.toString(firstName.charAt(3));
       
        this.txtCURP.setText(rfc+(btnHombre.isSelected()?"H":"M")+state+mIPA+mISA+mIN);
        new IntroWindow().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHombreActionPerformed
        // TODO add your handling code here:
        String genero;
        if(btnHombre.isSelected()){
            genero="H";
        }
    }//GEN-LAST:event_btnHombreActionPerformed

    private void btnMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMujerActionPerformed
        // TODO add your handling code here:
        String genero;
        if(btnMujer.isSelected()){
            genero="M";
        }
    }//GEN-LAST:event_btnMujerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnHombre;
    private javax.swing.JRadioButton btnMujer;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCURP;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtPApellido;
    private javax.swing.JTextField txtPNombre;
    private javax.swing.JTextField txtSApellido;
    private javax.swing.JTextField txtSNombre;
    // End of variables declaration//GEN-END:variables
}
